### ISSUE TITLE
Rsync exclude/include rules

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/backup-system#14]
Our current implementation allows for configuration based `rsync` include and exclude patterns, but has a very confusing strategy of re-rooting the source copy based on the inclusion pattern, and then only specifying the exclusion patterns in the rsync format. We have discussed that allowing for a backup to have a relative root at a subdirectory on a target machine causes some other issues with exclusion rules, and also then backup destination hierarchies.

For these reasons, and to reduce confusion when writing rules, I'd like to adjust the way that we specify these inclusion and exclusion patterns. I personally feel like the exclusion and inclusion rules for `rsync` are challenging to understand (order matters) and I'd like to adjust our configuration in an attempt to meet typical backup strategy needs with a bit more ease. I'm open to discussion on this before any implementation, but my current thinking on this subject follows:
* Our config files don't need a 1-to-1 match to the rsync parameters. I am thinking we have 3 categories of settings:
  * The top-level directories to be added to the backup. (Ideally top-level, but really any level can be specified). All of these patterns need to be inspected to ensure absolute paths, and adjusted to contain trailing double stars.
  * The file extensions to be ignored always. These need to be inspected to never specify absolute paths, and adjusted begin with wildcards (single star).
  * Specific file or directories to be ignored. Ex] `/home/sgdavis/.steam`. These patterns need to be inspected to ensure absolute paths, and no wildcards.
* Require users to opt-in any top-level directories that they want to include in the backup. For example, most everyone will want `/home` and probably `/etc/` but generally other top-level directories can be skipped. 
  * To achieve this, always append `--exclude="*"` as the last exclude pattern
  * Ensure pattern order is correct, these includes need to follow any file extension excludes, specific file excludes, and precede the final exclude wildcard.
  * Also, this behavior could be overridden if desired, by specifying `--include="/**"` to include all top-level directories

**Comment by osandvold302** [comment]
From the rsyncwrapper module, it looks like anything provided as a src attribute in rsyncOptions will be pushed onto the arguments list first, then excludeFirst options, then include attributes, then finally, exclude attributes. 

So we will have to change how we define src since we currently have it containing the array of all include options. 

Current solution is to provide the src as `user + '@' + machineIP`, include as the top level inclusion patterns appended to `user + '@' + machineIP + ':' `, excludeFirst as both file extensions and specific files/directories to ignore, and exclude as `--exclude="*"`

**Comment by osandvold302** [comment]
These options have been implemented and pushed to code base.
