### ISSUE TITLE
(Re)Organize dispatchers to take in object

### ISSUE THREAD

**Issue by osandvold** [bioneos/backup-system#3]
Object will contain 3 (or more) attributes:
1. long, detailed summary type message
2. shorter, < 140 character message
3. just the highlights? 

free to brainstorm other ideas

**Comment by sgdavis1** [comment]
How about we treat the "just the highlights" idea as a `subject` so that we can use that to address emails, and ignore it for SMS. I also could see us using both a styled HTML message, and a text message in the long formats, but unless we have a concrete example of where this would be used I don't want to introduce it yet. Therefore, I would suggest the documentation for this method indicates the following (required) properties on the Object:

```
{
  subject: "shortest text here",
  short: "140 characters or less here",
  long: "HTML styled long format message"
}
```

Be sure to include this in the code documentation. Thanks!

**Comment by smithmf** [comment]
I'm certainly a fan of having as much in our object as we want and letting our dispatcher pick out whatever keys are appropriate. I actually think if we're going to have a version that should be intended to be styled HTML, we actually have that keyed as `html` in the object.

**Comment by osandvold302** [comment]
Both email and console have been reconfigured to take in a message object. I have not worked on sms yet

**Comment by sgdavis1** [comment]
Made one more commit related to this (we missed converting a single call in system)
