### ISSUE TITLE
Configured keys cannot easily be used

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#6]
Generated keys need UID matching the container's user (node). 
During the docker file setup, generate a default key to be used; don't allow a configured key.

**Comment by sgdavis1** [comment]
I think I have figured out a strategy for this:
* Generate an SSH key for the `node` account while building the image (`Dockerfile` will need to be updated)
* Also modify the `Dockerfile` to adjust the SSH config so that it will automatically accept keys for unknown hosts (`StrictHostKeyChecking=no`)
* Store the key in the home directory so it is automatically used
* Update the console logging to output the public part of the key during startup (so it can be used to authenticate)
* In addition, when in `DEVEL` mode, warn the user that they should not use configured keys because of the potential permissions issues.

Optionally:
* Add a boot up check for file ownership / permissions on configured keys. This could error out on startup (because it will cause `rsync` failures until it is resolved), and this check can stay in place for production.

I believe this will solve all the issues we were seeing with your original setup. @osandvold302 if you want to take a crack at this, that works. Just let me review your code before you merge to devel.

**Comment by osandvold302** [comment]
I've written a first draft of an asynchronous function that attempts to find public SSH keys based on whether an identity path is specified and checking 4 different identities in protocol version 2. I will need to test this function to see if it properly returns public SSH keys and logs them in the console.

**Comment by osandvold302** [comment]
Implemented all on the list except for checking for file ownership/permissions.
