### ISSUE TITLE
After 1 successful backup, backup system continues to call backupProcess()

### ISSUE THREAD

**Issue by osandvold302** [bioneos/backup-system#8]
I believe that the problem lies somewhere in the now Date generation, as when I print the current time to the debugger the seconds do not change as the backupProcess method is implemented several (9) times. When the time changes to one second ahead, the backupProcess stops and all of the backupEvents are added to the database.

Maybe need for milliseconds?

**Comment by sgdavis1** [comment]
You nailed it. The problem was the function that generated the next scheduled time didn't reset milliseconds to 0 so it would generate new dates using the milliseconds of the current timestamp, and thus they would be a few ms in the future. Then it would set itself up to begin again as we reached that timestamp (up to the first 999ms after the scheduled time). Once we were a second or more past the scheduled time this behavior stopped.

But it is all fixed with my latest push so we can discuss this and your future tasks today!
